chaosblade-io/chaosblade-spec-go

spec/model.go

See chaosblade-io/chaosblade#255 for the details.
1. Replace spaces to `@@##` before record to database.
2. Replace `@@##` to spaces when used.

bugfix: fix flag values contains spaces

---

util/util.go

feature: add post curl function

---

channel/local.go

Signed-off-by: xcaspar <x.caspar@gmail.com>
chaosblade-io/chaosblade#321
Because of the blade command output is stdout, so only get output from stdout when the command executed is the blade command.
Execute correct and incorrect commands respectively.

bugfix: fix blade output for server mode

---

channel/local.go

Fix kill_process by localPort process not found issue, original code ss -np lost -l argument.
Fix kill_process by localPort process not found issue
Fixes #358 kill_process by localPort not working
add -nlp in the ss command

bugfix: fix kill_process by localPort process not found issue

---

channel/local.go

this PR support multiple exclude process

feature:support multiple exclude process

---

channel/local.go
go.mod
go.sum

Signed-off-by: xcaspar <x.caspar@gmail.com>
Resolve ps command not found issue.
chaosblade-io/chaosblade#319
Use gopsutil lib to replace ps command.
Integrate into the chaosblade tool for testing.

feature: replace ps command to gopsutil

---

spec/model.go
util/spec.go

Signed-off-by: tiny.x <185120555@qq.com>
add action example

feature:add action exeample

---

spec/executor.go
spec/model.go
util/spec.go
util/util.go

Signed-off-by: xcaspar <x.caspar@gmail.com>
chaosblade-io/chaosblade#410
1. Add programs field in expriment model for binding chaos program to chaos experiment.
2. Add yaml directory in chaosblade package to split with chaos program bin file.

feature: add programs field in action spec

---

spec/executor.go
spec/model.go
util/spec.go

Release v0.10.0 

---

channel/channel.go
channel/local.go
channel/local_mock.go
spec/model.go
spec/response.go
util/log.go
util/slice.go
util/util.go

At present, the error codes of the replies are messy, which requires unified and refactoring.
Fixes #489
Unified error code structure and error content

Unified error code

---

channel/channel.go
channel/local.go
channel/local_mock.go
spec/model.go
spec/response.go
util/log.go
util/slice.go
util/util.go

Reverts chaosblade-io/chaosblade-spec-go#20

Revert "Unified error code"

---

channel/channel.go
channel/local.go
channel/local_mock.go
spec/model.go
spec/response.go
util/log.go
util/slice.go
util/spec.go
util/util.go

V1.1.0 dev

---

channel/channel.go
channel/local.go
channel/local_mock.go
spec/model.go
spec/response.go
util/log.go
util/slice.go
util/spec.go
util/util.go

V1.2.0 dev

---

spec/response.go

https://github.com/chaosblade-io/chaosblade/issues/518

Add error number

---

channel/local.go
spec/response.go
util/slice.go
util/slice_test.go

Signed-off-by: xcaspar <changjun.xcj@alibaba-inc.com>
1. Simplify coding complexity.
2. Fix the original result output problem.
chaosblade-io/chaosblade#533
1. Refactor the error code struct.
2. Simplify the result return.
Compile and test it.

feature: update result return format

---

spec/response.go

fix: Missing a comma

---

channel/local.go
spec/response.go
util/slice.go
util/slice_test.go
util/util.go

Merge 1.3.0-dev branch

---

util/spec.go

Signed-off-by: xcaspar <changjun.xcj@alibaba-inc.com>
Solve the problem of flags conflict when using.

bugfix: fix conflict of flags

---

channel/channel.go
channel/local.go
spec/response.go
util/spec.go
util/util.go

Merge 1.4.0-dev branch

---

util/util.go

Signed-off-by: ms2008 <ms2008vip@gmail.com>
Fix: #36

fix: setting once initially for seed PRNG

---

channel/local_unixs.go
channel/local_windows.go
spec/constants.go

Add Windows Channel support
no
copy from Linux channel

feature: Add Windows Channel support

---

spec/constants.go

Signed-off-by: arthur657834 <kingkom7834@126.com>
add constant ChaosCloudBin

chore: add ChaosCloudBin

---

spec/constants.go
util/util.go

fixes:https://github.com/chaosblade-io/chaosblade/issues/853

add yaml path env

---

go.mod

Upgrade go version to 1.20
go.mod modify go 1.13  to go.20  ,then execute "go mod tidy"

upgrade go to v1.20

---

channel/local_unixs.go
channel/local_windows.go
channel/nsexec.go
spec/constants.go

fix Serialization error caused by non-JSON format data returned from executing a command.

fix: Non-JSON format character serialization error.

---

.github/workflows/ci.yml
util/util_test.go

Chore: Add ci.yml for compile testing
